apiVersion: v1
kind: Service
metadata:
  name: vx0-backbone
  namespace: vx0-network
  labels:
    app: vx0-backbone
    tier: backbone
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: bgp
    port: 1179
    targetPort: 1179
    protocol: TCP
  - name: ike
    port: 4500
    targetPort: 4500
    protocol: UDP
  - name: discovery
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: vx0-backbone

---
apiVersion: v1
kind: Service
metadata:
  name: vx0-backbone-internal
  namespace: vx0-network
  labels:
    app: vx0-backbone
    tier: backbone
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  - name: dns
    port: 5353
    targetPort: 5353
    protocol: UDP
  selector:
    app: vx0-backbone
