version: '3.8'

services:
  # VX0 Edge Node - for personal/home users
  vx0-edge:
    build: .
    container_name: vx0-edge-node
    restart: unless-stopped
    ports:
      - "1179:1179/tcp"    # BGP routing
      - "4500:4500/udp"    # IKE/IPSec
      - "5353:5353/udp"    # DNS
      - "8080:8080/tcp"    # Service discovery
      - "9090:9090/tcp"    # Metrics
    volumes:
      - ./config/edge-node.toml:/app/vx0net.toml:ro
      - ./certs:/app/certs:ro
      - vx0-edge-data:/app/data
      - vx0-edge-logs:/app/logs
    environment:
      - VX0NET_LOG_LEVEL=info
      - VX0NET_NODE_TIER=Edge
      - VX0NET_NODE_ASN=66001
    networks:
      - vx0-network
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
      - NET_RAW
    
  # VX0 Regional Node - for regional operators
  vx0-regional:
    build: .
    container_name: vx0-regional-node
    restart: unless-stopped
    ports:
      - "1180:1179/tcp"    # BGP routing (different port to avoid conflicts)
      - "4501:4500/udp"    # IKE/IPSec
      - "5354:5353/udp"    # DNS
      - "8081:8080/tcp"    # Service discovery
      - "9091:9090/tcp"    # Metrics
    volumes:
      - ./config/regional-node.toml:/app/vx0net.toml:ro
      - ./certs:/app/certs:ro
      - vx0-regional-data:/app/data
      - vx0-regional-logs:/app/logs
    environment:
      - VX0NET_LOG_LEVEL=info
      - VX0NET_NODE_TIER=Regional
      - VX0NET_NODE_ASN=65101
    networks:
      - vx0-network
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
      - NET_RAW
    profiles:
      - regional
    
  # VX0 Backbone Node - for infrastructure providers
  vx0-backbone:
    build: .
    container_name: vx0-backbone-node
    restart: unless-stopped
    ports:
      - "1181:1179/tcp"    # BGP routing
      - "4502:4500/udp"    # IKE/IPSec
      - "5355:5353/udp"    # DNS
      - "8082:8080/tcp"    # Service discovery
      - "9092:9090/tcp"    # Metrics
    volumes:
      - ./config/backbone-node.toml:/app/vx0net.toml:ro
      - ./certs:/app/certs:ro
      - vx0-backbone-data:/app/data
      - vx0-backbone-logs:/app/logs
    environment:
      - VX0NET_LOG_LEVEL=info
      - VX0NET_NODE_TIER=Backbone
      - VX0NET_NODE_ASN=65001
    networks:
      - vx0-network
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
      - NET_RAW
    profiles:
      - backbone

  # Monitoring stack (optional)
  prometheus:
    image: prom/prometheus:latest
    container_name: vx0-prometheus
    restart: unless-stopped
    ports:
      - "9093:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - vx0-network
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: vx0-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=vx0-admin-change-me
    networks:
      - vx0-network
    profiles:
      - monitoring

networks:
  vx0-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  vx0-edge-data:
  vx0-edge-logs:
  vx0-regional-data:
  vx0-regional-logs:
  vx0-backbone-data:
  vx0-backbone-logs:
  prometheus-data:
  grafana-data:
