# VX0 Network Production Configuration - Regional Node 1
# Deploy this on your second VPS

[node]
hostname = "regional1.vx0.network"
asn = 65101
tier = "Regional"
location = "US-West-1"
# REPLACE WITH YOUR VPS PUBLIC IP
ipv4_address = "YOUR_VPS_PUBLIC_IP"
ipv6_address = "fe80::2"

[network.bgp]
# REPLACE WITH YOUR VPS PUBLIC IP
router_id = "YOUR_VPS_PUBLIC_IP"
listen_port = 1179
hold_time = 90
keepalive_time = 30

[network.dns]
listen_port = 5353
vx0_dns_servers = ["10.0.0.2:53", "10.0.0.3:53"]
cache_size = 1000

[network.routing]
max_paths = 4
local_preference = 100
med = 0

[security.ike]
listen_port = 4500
dh_group = 14
encryption_algorithm = "AES-256"
hash_algorithm = "SHA-256"
prf_algorithm = "HMAC-SHA256"

[security.certificates]
ca_cert_path = "certs/ca.crt"
node_cert_path = "certs/regional1.crt"
node_key_path = "certs/regional1.key"

[security.encryption]
cipher = "AES-256-GCM"
key_size = 32
iv_size = 12

[services]
enable_discovery = true
discovery_port = 8081
service_ttl = 300

[monitoring]
enable_metrics = true
metrics_port = 9091
log_level = "info"

# Bootstrap nodes - connect to backbone nodes
[bootstrap]
nodes = [
    { hostname = "backbone1.vx0.network", ip = "BACKBONE1_VPS_IP", asn = 65001 },
    # { hostname = "backbone2.vx0.network", ip = "BACKBONE2_VPS_IP", asn = 65002 },
]

[security.psk]
default = "vx0-network-secure-key-change-in-production"